<Project>
  <Import Project="..\Directory.Build.props" />
  <PropertyGroup>
    <ImportDirectoryPackagesProps>false</ImportDirectoryPackagesProps>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <IsPackable>false</IsPackable>
    <IncludeSymbols>false</IncludeSymbols>
    <EmbedUntrackedSources>false</EmbedUntrackedSources>
  </PropertyGroup>
</Project>
