<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <WinUIMvvmExpressVersion>1.0.0</WinUIMvvmExpressVersion>
  </PropertyGroup>
</Project>
